[package]
name = "infra-upstream-repository-impl"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../../domain" }
prost = "0.14.0"
tonic = { version = "0.14.0", features = ["gzip"] }
tonic-prost = "0.14.0"
pbjson-types = "0.9.0"
envy = "0.4.2"
serde = "1.0.198"
anyhow = "1.0.82"
tracing = "0.1.39"
async-trait = "0.1.80"
chrono = "0.4.38"

